### Hypothesis

1. Which country has more attacks?
2. Attacks increase fatality depending on Year and Age?
3. Show attacks evolution by year (less/more sharks, less/mnore agressive)
4. Which type of acitvity is done when attack? Any activity more dangerous than others?

### Needed actions
1. Setup and Libraries
2. Get all info from dataset:
    - Read Dataset in a new frame
    - Describe
    - Shape
    - Columns 
    - Types
3. Fix columns
    - Strip and upper names
4. Null values and dropping
    - Check amount of NaN
    - Drop not needed colums
    - Drop rows with all Nan
5. Fixing content needed columns
    - Replace Nan with '' or 0
    - Case Number to date
    - COUNTRY
    - Year
    - Age
    - Type
    - Activity
6. Visualize hypothesis using charts

**1. Setup and Libraries:**

In [1]:
#Libraries required

import pandas as pd
import numpy as np 
import re as r
from pere import *


#setup visualize
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_colwidth', None)

#Read data from external source
df_sharks = pd.read_csv("../data/attacks.csv", sep=",", encoding="Latin-1")
df_sharks.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and paddle damaged",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adysonï¿½McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [2]:

df_sharks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [3]:
#Fix columns names: strip and uppercase

fix_cols(df_sharks)
change_col(df_sharks,"FATAL (Y/N)","FATAL")
change_col(df_sharks,"INVESTIGATOR OR SOURCE","SOURCE")

In [4]:
print(f"{df_sharks['HREF'].isin(df_sharks['HREF FORMULA']).value_counts()}") # pretty similar columns
print(f"{df_sharks['CASE NUMBER'].isin(df_sharks['CASE NUMBER.1']).value_counts()}") # pretty similar columns
print(f"{df_sharks['CASE NUMBER'].isin(df_sharks['CASE NUMBER.2']).value_counts()}") # pretty similar columns
print(f"{df_sharks['CASE NUMBER.1'].isin(df_sharks['CASE NUMBER.2']).value_counts()}") # pretty similar columns

True     25666
False       57
Name: HREF, dtype: int64
True     23299
False     2424
Name: CASE NUMBER, dtype: int64
True     23319
False     2404
Name: CASE NUMBER, dtype: int64
True     25704
False       19
Name: CASE NUMBER.1, dtype: int64

In [5]:

#Selecting columns to work: dropping

df_sharks.drop(['UNNAMED: 22','UNNAMED: 23','HREF FORMULA','CASE NUMBER.1','CASE NUMBER.2','PDF','ORIGINAL ORDER','SOURCE'], axis=1,inplace=True) # These columns don't have interestin data for our goal

In [6]:
# Null values actions

# % of null values in every column
def check_null_values():
    v_dict = {}
    for col in df_sharks.columns:
        v_missed = np.mean(df_sharks[col].isna())
        v_dict[col]=str(round(v_missed*100))+"%"
    return v_dict

check_null_values()

{'CASE NUMBER': '66%',
 'DATE': '76%',
 'YEAR': '76%',
 'TYPE': '76%',
 'COUNTRY': '76%',
 'AREA': '77%',
 'LOCATION': '78%',
 'ACTIVITY': '78%',
 'NAME': '76%',
 'SEX': '78%',
 'AGE': '87%',
 'INJURY': '76%',
 'FATAL': '78%',
 'TIME': '89%',
 'SPECIES': '87%',
 'HREF': '76%'}

In [7]:
#Clean empty rows
df_sharks.dropna(how="all",inplace=True)

### Fixing content inside columns

### CASE NUMBER fixing

In [8]:
pd.set_option('display.max_rows', 100)
df_sharks["CASE NUMBER"].replace('0',np.nan,inplace=True)
df_sharks["CASE NUMBER"].replace('xx',np.nan,inplace=True)
df_sharks["CASE NUMBER"] = df_sharks["CASE NUMBER"].str[:10] 
df_sharks['CASE NUMBER'] = df_sharks['CASE NUMBER'].str.replace('-', '.', case=False, regex=True)
df_sharks['CASE NUMBER'] = df_sharks['CASE NUMBER'].str.replace(',', '.', case=False, regex=True)
df_sharks.dropna(how="all",inplace=True)
df_sharks.fillna("Unknown",inplace=True)
df_sharks.reindex()

,CASE NUMBER,DATE,YEAR,TYPE,COUNTRY,AREA,LOCATION,ACTIVITY,NAME,SEX,AGE,INJURY,FATAL,TIME,SPECIES,HREF
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and paddle damaged",N,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adysonï¿½McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,Unknown,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,Unknown,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,Unknown,Minor injury to lower leg,N,Unknown,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,Unknown,Lacerations to leg & hand shark PROVOKED INCIDENT,N,Unknown,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,Unknown,FATAL,Y,Unknown,Unknown,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0005-RoebuckBay.pdf
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,FATAL,Y,Unknown,Unknown,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0004-Ahmun.pdf
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,FATAL,Y,Unknown,Unknown,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,Unknown,"Panama Bay 8ï¿½N, 79ï¿½W",Unknown,Jules Patterson,M,Unknown,FATAL,Y,Unknown,Unknown,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away the lower extremities""",Y,Unknown,Unknown,http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf

In [9]:

try:
    for x in df_sharks.index:  
        
        if len(df_sharks["CASE NUMBER"].values[x]) == 10:

            v_year = r.search('(\d{4})\.(\d{2})\.(\d{2})',df_sharks.loc[x, "CASE NUMBER"]).group(1)
            v_month = r.search('(\d{4})\.(\d{2})\.(\d{2})',df_sharks.loc[x, "CASE NUMBER"]).group(2)
            v_day = r.search('(\d{4})\.(\d{2})\.(\d{2})',df_sharks.loc[x, "CASE NUMBER"]).group(3)
            df_sharks.loc[x, "YEAR_"] = v_year
            df_sharks.loc[x, "MONTH_"] = v_month
            df_sharks.loc[x, "DAY_"] = v_day
            df_sharks.loc[x, "YEAR"] = v_year
            df_sharks.loc[x, "DATE"] = v_day+"/"+v_month+"/"+v_year
        else:
            df_sharks.loc[x, "YEAR_"] = 0
            df_sharks.loc[x, "MONTH_"] = 0
            df_sharks.loc[x, "DAY_"] = 0
            df_sharks.loc[x, "YEAR"] = 0
            df_sharks.loc[x, "DATE"] = 0
except:
    print(x,"-",df_sharks["CASE NUMBER"].values[x])


df_sharks.drop(df_sharks[df_sharks["YEAR"] == 0].index, inplace=True)
df_sharks.drop(df_sharks[df_sharks["YEAR"] == '0077'].index, inplace=True)
df_sharks.drop(df_sharks[df_sharks["YEAR"] == '0500'].index, inplace=True)
df_sharks.drop(df_sharks[df_sharks["YEAR"] == '0005'].index, inplace=True)
df_sharks["YEAR"]=df_sharks["YEAR"].astype(int)

### ACTIVITY column

In [12]:
df_sharks["ACTIVITY"].fillna('Unknown',inplace=True)

for i in df_sharks.index:
        v_string = df_sharks.loc[i, "ACTIVITY"]
        df_sharks.loc[i, "ACTIVITY"] = fix_activity(v_string)

### COUNTRY column fixing

In [14]:
#Cleaning COUNTRY column

df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.strip()
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('?', '',regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*UAE.*', 'UNITED ARAB EMIRATES',case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('TOBAGO', 'TRINIDAD & TOBAGO',case=False,regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*VANUATU.*', 'SOLOMON ISLANDS' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*RED SEA.*', 'RED SEA' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*REUNION.*', 'REUNION' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*ITALY.*', 'ITALY' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*IRAN.*', 'IRAN' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*EGYPT.*', 'EGYPT' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*CEYLON.*', 'CEYLON' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*ANDAMAN.*', 'ANDAMAN ISLANDS' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*EQUATORIAL GUINEA.*', 'EQUATORIAL GUINEA' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*MALDIVE ISLANDS.*', 'MALDIVES' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('.*ST HELENA.*', 'ST HELENA' ,case=False, regex=True)
df_sharks['COUNTRY'] = df_sharks['COUNTRY'].str.replace('Fiji', 'FIJI',regex=True)
df_sharks.drop(df_sharks[(df_sharks['COUNTRY']=='AFRICA')].index, inplace=True)
df_sharks.drop(df_sharks[(df_sharks['COUNTRY']=='Coast of AFRICA')].index, inplace=True)
df_sharks.drop(df_sharks[(df_sharks['COUNTRY']=='Between PORTUGAL & INDIA')].index, inplace=True)
df_sharks["COUNTRY"].fillna('Unknown',inplace=True)

### SEX column fixing

In [28]:
df_sharks["SEX"] = df_sharks["SEX"].str.strip()
df_sharks['SEX'] = df_sharks['SEX'].str.replace('.*lli.*', 'M',regex=True)
df_sharks['SEX'] = df_sharks['SEX'].str.replace('.*N.*', 'M',regex=True)
df_sharks.drop(df_sharks[(df_sharks['SEX']=='.')].index, inplace=True)

### AGE column fixing

In [20]:
df_sharks['AGE'] = pd.to_numeric(df_sharks["AGE"].astype(str).str.replace(',',''), errors='coerce').fillna(0).astype(int)

### FATAL column cleaning

In [23]:
df_sharks['FATAL'] = df_sharks['FATAL'].str.strip()
df_sharks['FATAL'] = df_sharks['FATAL'].str.upper()
df_sharks['FATAL'] = df_sharks['FATAL'].replace('M','N')
df_sharks['FATAL'] = df_sharks['FATAL'].replace('2017','N')
df_sharks.FATAL.fillna('Unknown')

### WRITE TO CSV

In [26]:
df_sharks.to_csv("../data/attacks_chart.csv")